<?php

/**
 * @file
 * Provides an check payment method for Drupal Commerce for testing and
 *   development.
 */


/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_payment_check_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_payment_check'] = array(
    'title' => t('Write a check to "Apostolic Christian Church" for the Subtotal amount and select Continue for the mailing address.'),
    'description' => t('You can use a check to pay.'),
    'active' => TRUE,
  );

  return $payment_methods;
}

/**
 * Payment method callback: submit form.
 */
function commerce_payment_check_submit_form($payment_method, $pane_values, $checkout_pane, $order) {

  // Default to a known test credit card number. For valid numbers of other card
  // types see: http://www.rimmkaufman.com/blog/credit-card-test-numbers/09112007/
  drupal_set_message(t('You can mail a check to save the credit card processing fees. Select paypal, to pay online via credit card with a 3.5% fee..'));
  return $form['mode_type'];

}

/**
 * Payment method callback: submit form validation.
 */
function commerce_payment_check_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  //echo '<pre>' . print_r(get_defined_vars(), true) . '</pre>'; die;
  //echo '<pre>' . print_r(get_defined_functions()). '</pre>'; die;
  commerce_discount_commerce_cart_order_empty($order);

  return TRUE;
}

/**
 * Payment method callback: submit form submission.
 */
function commerce_payment_check_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  // Just as an check, we might store information in the order object from the
  // payment parameters, though we would never save a full credit card number,
  // even in checks!
  $number = $pane_values['credit_card']['number'];
  $pane_values['credit_card']['number'] = substr($number, 0, 4) . str_repeat('-', strlen($number) - 8) . substr($number, -4);

  $order->data['commerce_payment_check'] = $pane_values;

  // Every attempted transaction should result in a new transaction entity being
  // created for the order to log either the success or the failure.
  commerce_payment_check_transaction($payment_method, $order, $charge);
}

/**
 * Creates an check payment transaction for the specified charge amount.
 *
 * @param $payment_method
 *   The payment method instance object used to charge this payment.
 * @param $order
 *   The order object the payment applies to.
 * @param $charge
 *   An array indicating the amount and currency code to charge.
 */
function commerce_payment_check_transaction($payment_method, $order, $charge) {
  $card_details = $order->data['commerce_payment_check']['credit_card'];

  $transaction = commerce_payment_transaction_new('commerce_payment_check', $order->order_id);
  $transaction->instance_id = $payment_method['instance_id'];
  $transaction->amount = $charge['amount'];
  $transaction->currency_code = $charge['currency_code'];
  $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;

  $transaction->message = 'Number: @number<br/>Expiration: @month/@year';
  $transaction->message_variables = array(
    '@number' => $card_details['number'],
    '@month' => $card_details['exp_month'],
    '@year' => $card_details['exp_year'],
  );

  commerce_payment_transaction_save($transaction);
  return $transaction;
}
